/***************************************************************************
 * fifteen.c
 *
 * Computer Science 50
 * Problem Set 3
 *
 * Implements The Game of Fifteen (generalized to d x d).
 *
 * Usage: fifteen d
 *
 * whereby the board's dimensions are to be d x d,
 * where d must be in [DIM_MIN,DIM_MAX]
 *
 * Note that usleep is obsolete, but it offers more granularity than
 * sleep and is simpler to use than nanosleep; `man usleep` for more.
 ***************************************************************************/
 
#define _XOPEN_SOURCE 500

#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>


// constants
#define DIM_MIN 3
#define DIM_MAX 9

// board
int board[DIM_MAX][DIM_MAX];

// dimensions
int d;


// prototypes
void clear(void);
void greet(void);
void init(void);
void draw(void);
bool move(int tile);
bool won(void);

// my additional prototypes
void solve(void);
bool check_solvable(int list[]);
void shuffle(int list[]);
void position_blank(int row, int column, int blocked[]);
int find_row(int number);
int find_column(int number);


int
main(int argc, char *argv[])
{
	// seed the random number generator
	srand(time(NULL));
	
    // greet user with instructions
    greet();

    // ensure proper usage
    if (argc != 2)
    {
        printf("Usage: %s d\n", argv[0]);
        return 1;
    }

    // ensure valid dimensions
    d = atoi(argv[1]);
    if (d < DIM_MIN || d > DIM_MAX)
    {
        printf("Board must be between %d x %d and %d x %d, inclusive.\n",
         DIM_MIN, DIM_MIN, DIM_MAX, DIM_MAX);
        return 2;
    }

    // initialize the board
    init();

    // accept moves until game is won
    while (true)
    {
        // clear the screen
        clear();

        // draw the current state of the board
        draw();

        // check for win
        if (won())
        {
            printf("ftw!\n");
            break;
        }

        // prompt for move
        printf("Tile to move: ");
        int tile = GetInt();

        // move if possible, else report illegality
        if (!move(tile))
        {
            printf("\nIllegal move.\n");
            usleep(500000);
        }

        // sleep thread for animation's sake
        usleep(500000);
    }

    // that's all folks
    return 0;
}


/*
 * Clears screen using ANSI escape sequences.
 */

void
clear(void)
{
    printf("\033[2J");
    printf("\033[%d;%dH", 0, 0);
}


/*
 * Greets player.
 */

void
greet(void)
{
    clear();
    printf("WELCOME TO THE GAME OF FIFTEEN\n");
    usleep(2000000);
}


/*
 * Initializes the game's board with tiles numbered 1 through d*d - 1
 * (i.e., fills 2D array with values but does not actually print them).  
 */

void
init(void)
{
	
	// A pseudorandom starting position will be generated by using the 
	// Knuth shuffle on an initally unshuffled list
	int list[d*d];
	for(int i = 0; i < d*d - 1; i++)
		list[i] = i + 1;
	
	list[d*d - 1] = 0;
	
	//for(int i = 0; i < d*d; i++)
	//	printf("%d ", list[i]);
	//usleep(2000000);
	
	bool success = false;
	//success = true;    // for testing
	while(!success)
	{
		//printf("no success yet...\n");
		//usleep(2000000);
		shuffle(list);
		if(check_solvable(list) == true)
			success = true;
	}
	
	// copy list into the board
	for(int i = 0; i < d; i++)
	{
		for(int j = 0; j < d; j++)
		{
			board[i][j] = list[d*i + j];
		}
	}
}


/* 
 * Prints the board in its current state.
 */

void
draw(void)
{
	printf("\033[1;36m\n\n");
	for(int i = 0; i < d; i++)
	{
		for(int j = 0; j < d; j++)
		{
			if(board[i][j] == 0)
				printf("\033[4m  \033[0m  \033[1;36m");
			else
				printf("%2d  ", board[i][j]);
		}
		printf("\n");
	}
	printf("\033[0m\n\n");
}


/* 
 * If tile borders empty space, moves tile and returns true, else
 * returns false. 
 */

bool
move(int tile)
{
	for(int i = 0; i < d; i++)
		for(int j = 0; j < d; j++)
			if(board[i][j] == tile)
			{
				if((i + 1 < d) && (board[i + 1][j] == 0))
				{
					board[i + 1][j] = board[i][j];
					board[i][j] = 0;
					return true;
				}
				else if((i - 1 >= 0) && (board[i - 1][j] == 0))
				{
					board[i - 1][j] = board[i][j];
					board[i][j] = 0;
					return true;
				}
				else if((j + 1 < d) && (board[i][j + 1] == 0))
				{
					board[i][j + 1] = board[i][j];
					board[i][j] = 0;
					return true;
				}
				else if((j - 1 >= 0) && (board[i][j - 1] == 0))
				{
					board[i][j - 1] = board[i][j];
					board[i][j] = 0;
					return true;
				}
			}
    return false;
}


/*
 * Returns true if game is won (i.e., board is in winning configuration), 
 * else false.
 */

bool
won(void)
{
	for(int i = 0; i < d; i++)
	{
		for(int j = 0; j < d; j++)
		{
			if((i == d - 1) && (j == d - 1))
			{
				if(board[d-1][d-1] != 0)
				{
					//printf("Apparently the last element is not 0\n");
					//usleep(2000000);
					return false;
				}
			}
			else
			{
				if(board[i][j] != (d*i + j + 1))
				{	
					//printf("Apparently board[%d][%d] is not %d\n", i, j, d*i + j + 1);
					//usleep(2000000);
					return false;
				}
			}
		}
	}		
    return true;
}


/*
 * Checks a pseudo-randomly generated board for solvability
 *
 */

bool
check_solvable(int list[])
{
	
	// Find how many inversions there are in the passed board
	
	int count = 0;
	for(int i = 0; i < d*d - 1; i++)
	{
		for(int j = i; j < d*d - 1; j++)
		{
			if(list[i] > list[j])
				count++;
		}
	}
	
	// If the number of inversions is even, return true
	// else, return false
	
	if(count % 2 == 0)
	{
		return true;
	}
	else
	{
		return false;
	}
}


/*
 * A function to shuffle a list, uniformly performing a random permutation
 *
 */

void
shuffle(int list[])
{
	for(int i = d*d - 2; i > 0; i--)
	{
		int j = rand() % i;
		int temp = list[i];
		list[i] = list[j];
		list[j] = temp;
	}
}


/*
 * A function to solve the puzzle automatically
 *
 */

void
solve(void)
{
	// An array representing the squares that have been put into place
	int blocked[d][d];
	for(int i = 0; i < d; i ++)
		for(int j = 0; j < d; j++)
			blocked[i][j] = 0;
	
	// First solve all but the last two rows
	for(int i = 0; i < d - 2; i++)
	{
		for(int j = 0; j < d - 1; j++)
		{
			int cur_row = find_row(d*i + j + 1);
			int cur_column = find_column(d*i + j + 1);
			while(cur_column != j)
			{
				if(cur_column < j)
				{
					position_blank
				}
			}
		}
	}
	
}


/*
 * Functions to find which row and column a number is currently in
 */

int
find_row(int number)
{
	for(int i = 0; i < d; i++)
		for(int j = 0; j < d; j++)
			if(board[i][j] == number)
				return i;
}


int
find_column(int number)
{
	for(int i = 0; i < d; i++)
		for(int j = 0; j < d; j++)
			if(board[i][j] == number)
				return j;
}


/*
 * Position the blank at a particular spot, given a list of blocked spots
 */

void
position_blank(int row, int column, int blocked[])
{
	
}